[package]
name = "libra"
version = "0.1.0"
edition = "2024"

[features]
default = []

[dependencies]
git-internal = "0.1.0"
ahash = "0.8"
anyhow = "1.0"
axum = "0.8.4"
bincode = "2.0"
bstr = "1.0"
byte-unit = "5.0"
byteorder = "1.5"
bytes = "1.0"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.0", features = ["derive"] }
colored = "3.0"
dashmap = "6.1"
encoding_rs = "0.8"
flate2 = "1.0"  # add features = ["zlib"] if slow
futures = "0.3"
futures-util = "0.3"
hex = "0.4"
http = "1.0"
ignore = "0.4"
indicatif = "0.18"
lazy_static = "1.4"
libc = "0.2"
lru-mem = "0.3"
memchr = "2.0"
num_cpus = "1.0"
once_cell = "1.0"
pager = "0.16"  # only on Unix
path-absolutize = "3.0"
pathdiff = "0.2"
quickcheck = "1.0"
rand = "0.9.2"
rand_chacha = "0.9.0"
rayon = "1.0"
regex = "1.0"
reqwest = { version = "0.12.23", features = ["stream", "json"] }
ring = "0.17"
rpassword = "7.0"
scopeguard = "1.0"
sea-orm = { version = "1.1.16", features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "macros",
] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha1 = "0.10"
similar = "2.0"
tempfile = "3.0"
serial_test = "3.0"
testcontainers = "0.25"
thiserror = "2.0"
threadpool = "1.0"
tokio = { version = "1.0", features = ["rt-multi-thread", "rt", "macros"] }
tokio-util = { version = "0.7", features = ["io"] }
tracing = "0.1"
tracing-subscriber = "0.3"
url = "2.0"
uuid = "1.0"
walkdir = "2.0"
wax = "0.6"
zstd-sys = "2.0.15"
idgenerator = "2.0"
diffs = "0.5"
async-trait = "0.1"
aws-config = "1.0"
aws-sdk-s3 = "1.0"
base64 = "0.22"
bs58 = "0.5"
config = "0.14"
directories = "5.0"
envsubst = "0.2"
indexmap = "2.0"
infer = "0.16"
openssl = "0.10"
pgp = "0.15.0"
quinn = "0.11"
rcgen = "0.13"
sea-orm-migration = "1.1.16"
secp256k1 = "0.29"
smallvec = "1.13"
sysinfo = "0.32"
tokio-stream = "0.1"
cedar-policy = "4.0"
itertools = "0.13"
utoipa = "5.1"

[target.'cfg(unix)'.dependencies] # only on Unix
pager = "0.16"

[dev-dependencies]
tempfile = "3.0"
serial_test = "3.0"
tokio = { version = "1.0", features = ["macros", "process"] }
testcontainers = { version = "0.25", features = [
    "http_wait",
    "reusable-containers",
] }
reqwest = { version = "0.12.23", features = ["blocking"] }
